// <auto-generated />
namespace PokerProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addTournamentEntry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTournamentEntry));
        
        string IMigrationMetadata.Id
        {
            get { return "202102102102378_addTournamentEntry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
